/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author candr
 */
public class Main_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Main_Menu
     */
    private Date d;
    private SimpleDateFormat sdf;
    private Timer t;
    private ImageIcon ic;
    private ActionListener taskPerformer;
    private String nol_jam = "", nol_menit = "", nol_detik = "";
    private String jam, menit, detik;
    private int nilai_jam, nilai_menit, nilai_detik;
    private int pilihan, keluar;
    
    // ConsTruktor
    public Main_Menu() 
    {
        initComponents();
        // Tutup Frame
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        //menambahkan perintah penutupan
        this.addWindowListener(new WindowAdapter() 
        {
            public void windowClosing(WindowEvent evt) 
            {
                pilihan = JOptionPane.showConfirmDialog(null, "Apakah anda ingin keluar dan kembali ke halaman login ?", "Log Out", JOptionPane.YES_NO_OPTION);
                if(pilihan == JOptionPane.YES_OPTION)
                {
                   Login l = new Login();
                   l.setVisible(true);
                   l.KosongkanData();
                   dispose(); 
                }
                
            }
        });
        this.setTitle("Main Menu");
        this.setLocationRelativeTo(null);
        TampilTanggal();
        TampilWaktu();
        ic = new ImageIcon((getClass().getResource("Img/2-modified (1).png")));
        this.setIconImage(ic.getImage());
    }
    
    // Method Menampilkan Tanggal
    private void TampilTanggal()
    {
        d = new Date();
        sdf = new SimpleDateFormat("EEEE, dd MMMM yyyy");
        LabelTanggal.setText(sdf.format(d.getTime()));
        
    }
    
    // Method Menampilkan Waktu
    private void TampilWaktu()
    { 
        taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                d = new Date();
                nilai_jam = d.getHours();
                nilai_menit = d.getMinutes();
                nilai_detik = d.getSeconds();
                
                if(nilai_jam <= 9)
                {
                    nol_jam = "0";
                }
                
                if(nilai_menit <= 9)
                {
                    nol_menit = "0";
                }
                
                if(nilai_detik <= 9)
                {
                    nol_detik = "0";
                }
                
                jam = nol_jam + Integer.toString(nilai_jam);
                menit = nol_menit + Integer.toString(nilai_menit);
                detik = nol_detik + Integer.toString(nilai_detik);
                
                LabelWaktu.setText(jam + " : " + menit + " : " + detik);
            }
        };
        new Timer(1000, taskPerformer).start();
    }

    
    // Method Exit Program
    private void ExitProgram()
    {
        keluar = JOptionPane.showConfirmDialog(null, "Apakah anda akan keluar dari program ?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);
        if(keluar == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfuser = new javax.swing.JLabel();
        tflevel = new javax.swing.JLabel();
        LabelSambutan = new javax.swing.JLabel();
        LabelSambutan1 = new javax.swing.JLabel();
        LabelTanggal = new javax.swing.JLabel();
        LabelWaktu = new javax.swing.JLabel();
        tfemail = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        File = new javax.swing.JMenu();
        MenuLogOut = new javax.swing.JMenuItem();
        MenuTambahUser = new javax.swing.JMenuItem();
        MenuExit = new javax.swing.JMenuItem();
        MasterUtama = new javax.swing.JMenu();
        MenuMasterBarang = new javax.swing.JMenuItem();
        MenuMasterPelanggan = new javax.swing.JMenuItem();
        MasterPenjualan = new javax.swing.JMenu();
        MenuCheckPelanggan = new javax.swing.JMenuItem();
        MenuCheckBarang = new javax.swing.JMenuItem();
        MenuTransaksiPenjualan = new javax.swing.JMenuItem();
        Tentang = new javax.swing.JMenu();
        MenuTentangAplikasi = new javax.swing.JMenuItem();
        MenuTentangDeveloper = new javax.swing.JMenuItem();
        MenuUlasan = new javax.swing.JMenuItem();
        Laporan = new javax.swing.JMenu();
        MenuLaporanBarang = new javax.swing.JMenuItem();
        MenuLaporanPelanggan = new javax.swing.JMenuItem();
        MenuLaporanTransaksi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 247, 202));

        tfuser.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        tfuser.setText("Nama");

        tflevel.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        tflevel.setText("Level");

        LabelSambutan.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        LabelSambutan.setText("Hallo, Selamat Datang,");

        LabelSambutan1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        LabelSambutan1.setText("di Aplikasi Go Market");

        LabelTanggal.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        LabelTanggal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelTanggal.setText("Tanggal");

        LabelWaktu.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        LabelWaktu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelWaktu.setText("Waktu");

        tfemail.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        tfemail.setForeground(new java.awt.Color(51, 102, 255));
        tfemail.setText("Email");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/Img/300x300.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/Img/Username.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/Img/email25x25.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/Img/level25x25.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/Img/tanggal.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/Img/waktu.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tfuser, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tflevel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelSambutan)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(LabelSambutan1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelWaktu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelTanggal)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelWaktu)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelSambutan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelSambutan1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfuser, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tflevel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(34, 34, 34))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 247, 202));
        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setBorderPainted(false);

        jMenu1.setBackground(new java.awt.Color(255, 247, 202));
        jMenu1.setBorder(null);
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/Img/25x25.png"))); // NOI18N
        jMenuBar1.add(jMenu1);

        File.setText("File");

        MenuLogOut.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        MenuLogOut.setText("Log Out");
        MenuLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuLogOutMouseClicked(evt);
            }
        });
        MenuLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLogOutActionPerformed(evt);
            }
        });
        File.add(MenuLogOut);

        MenuTambahUser.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        MenuTambahUser.setText("Tambah User ");
        MenuTambahUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTambahUserActionPerformed(evt);
            }
        });
        File.add(MenuTambahUser);

        MenuExit.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        MenuExit.setText("Exit");
        MenuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuExitMouseClicked(evt);
            }
        });
        MenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExitActionPerformed(evt);
            }
        });
        File.add(MenuExit);

        jMenuBar1.add(File);

        MasterUtama.setText("Master Utama");

        MenuMasterBarang.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        MenuMasterBarang.setText("Master Barang");
        MenuMasterBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMasterBarangActionPerformed(evt);
            }
        });
        MasterUtama.add(MenuMasterBarang);

        MenuMasterPelanggan.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        MenuMasterPelanggan.setText("Master Pelanggan");
        MenuMasterPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMasterPelangganActionPerformed(evt);
            }
        });
        MasterUtama.add(MenuMasterPelanggan);

        jMenuBar1.add(MasterUtama);

        MasterPenjualan.setText("Master Penjualan");

        MenuCheckPelanggan.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        MenuCheckPelanggan.setText("Check Pelanggan");
        MenuCheckPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCheckPelangganActionPerformed(evt);
            }
        });
        MasterPenjualan.add(MenuCheckPelanggan);

        MenuCheckBarang.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        MenuCheckBarang.setText("Check Barang");
        MenuCheckBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCheckBarangActionPerformed(evt);
            }
        });
        MasterPenjualan.add(MenuCheckBarang);

        MenuTransaksiPenjualan.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        MenuTransaksiPenjualan.setText("Transaksi Penjualan");
        MenuTransaksiPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTransaksiPenjualanActionPerformed(evt);
            }
        });
        MasterPenjualan.add(MenuTransaksiPenjualan);

        jMenuBar1.add(MasterPenjualan);

        Tentang.setText("Tentang");

        MenuTentangAplikasi.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        MenuTentangAplikasi.setText("Tentang Aplikasi");
        MenuTentangAplikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTentangAplikasiActionPerformed(evt);
            }
        });
        Tentang.add(MenuTentangAplikasi);

        MenuTentangDeveloper.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        MenuTentangDeveloper.setText("Tentang Developer");
        MenuTentangDeveloper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTentangDeveloperActionPerformed(evt);
            }
        });
        Tentang.add(MenuTentangDeveloper);

        MenuUlasan.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        MenuUlasan.setText("Ulasan");
        MenuUlasan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUlasanActionPerformed(evt);
            }
        });
        Tentang.add(MenuUlasan);

        jMenuBar1.add(Tentang);

        Laporan.setText("Laporan (Segera Hadir)");

        MenuLaporanBarang.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        MenuLaporanBarang.setText("Laporan Barang");
        Laporan.add(MenuLaporanBarang);

        MenuLaporanPelanggan.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        MenuLaporanPelanggan.setText("Laporan Pelanggan");
        Laporan.add(MenuLaporanPelanggan);

        MenuLaporanTransaksi.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        MenuLaporanTransaksi.setText("Laporan Transaksi");
        Laporan.add(MenuLaporanTransaksi);

        jMenuBar1.add(Laporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Sub Menu Tentang Developer
    private void MenuTentangDeveloperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTentangDeveloperActionPerformed
      Tentang_Dev td = new Tentang_Dev();
      td.setVisible(true);
    }//GEN-LAST:event_MenuTentangDeveloperActionPerformed

    // Sub Menu Tentang Aplikasi
    private void MenuTentangAplikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTentangAplikasiActionPerformed
        Tentang_Aplikasi ta = new Tentang_Aplikasi();
        ta.setVisible(true);   
    }//GEN-LAST:event_MenuTentangAplikasiActionPerformed

    // Sub Menu Check Barang
    private void MenuCheckBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCheckBarangActionPerformed
        Check_Barang cb = new Check_Barang();
        cb.setVisible(true);
    }//GEN-LAST:event_MenuCheckBarangActionPerformed

    // Sub Menu Master Pelanggan
    private void MenuMasterPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMasterPelangganActionPerformed
        if(tflevel.getText().equals("Kasir"))
        {
            Pelanggan p = new Pelanggan();
            p.btndelete.setVisible(false);
            p.setVisible(true);
        }
        else 
        {
            Pelanggan p = new Pelanggan();
            p.setVisible(true);
        }
    }//GEN-LAST:event_MenuMasterPelangganActionPerformed

    // Sub Menu Tambah User
    private void MenuTambahUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTambahUserActionPerformed
        Registrasi r = new Registrasi();
        r.setVisible(true);
    }//GEN-LAST:event_MenuTambahUserActionPerformed

    // Tidak Terpakai
    private void MenuLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLogOutMouseClicked

    }//GEN-LAST:event_MenuLogOutMouseClicked

    // Tidak Terpakai
    private void MenuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuExitMouseClicked
        
    }//GEN-LAST:event_MenuExitMouseClicked

    // Sub Menu Master Barang
    private void MenuMasterBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMasterBarangActionPerformed
       if(tflevel.getText().equals("Kasir"))
       {
           Barang b = new Barang();
           b.btnedit.setVisible(false);
           b.btndelete.setVisible(false);        
           b.setVisible(true);
       }
       else
       {
           Barang b = new Barang();
           b.setVisible(true);
       }
        
       
    }//GEN-LAST:event_MenuMasterBarangActionPerformed

    // Sub Menu LogOut
    private void MenuLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLogOutActionPerformed
        JOptionPane.showConfirmDialog(null, "Apakah anda ingin kembali ke halaman login ?", "Log Out", JOptionPane.YES_NO_OPTION);
        if(pilihan == JOptionPane.YES_OPTION)
        {
        Login l = new Login();
        l.setVisible(true);
        dispose(); 
        }
    }//GEN-LAST:event_MenuLogOutActionPerformed

    // Sub Menu Check Pelanggan
    private void MenuCheckPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCheckPelangganActionPerformed
        Check_Pelanggan cp = new Check_Pelanggan();
        cp.setVisible(true);
    }//GEN-LAST:event_MenuCheckPelangganActionPerformed

    // Sub Menu Transaksi Penjualan
    private void MenuTransaksiPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTransaksiPenjualanActionPerformed
        if(tflevel.getText().equals("Kasir"))
        {
            Transaksi t = new Transaksi();
            t.btnedit.setVisible(false);
            t.btndelete.setVisible(false);
            t.setVisible(true);
        }
        else
        {
            Transaksi t = new Transaksi();
            t.setVisible(true);
        }
        
        
    }//GEN-LAST:event_MenuTransaksiPenjualanActionPerformed

    // Sub Menu Ulasan
    private void MenuUlasanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUlasanActionPerformed
        Ulasan u = new Ulasan();
        u.setVisible(true);
    }//GEN-LAST:event_MenuUlasanActionPerformed

    // Sub Menu Exit Program
    private void MenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExitActionPerformed
        ExitProgram();
    }//GEN-LAST:event_MenuExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu File;
    private javax.swing.JLabel LabelSambutan;
    private javax.swing.JLabel LabelSambutan1;
    private javax.swing.JLabel LabelTanggal;
    private javax.swing.JLabel LabelWaktu;
    public javax.swing.JMenu Laporan;
    private javax.swing.JMenu MasterPenjualan;
    private javax.swing.JMenu MasterUtama;
    private javax.swing.JMenuItem MenuCheckBarang;
    private javax.swing.JMenuItem MenuCheckPelanggan;
    private javax.swing.JMenuItem MenuExit;
    private javax.swing.JMenuItem MenuLaporanBarang;
    private javax.swing.JMenuItem MenuLaporanPelanggan;
    private javax.swing.JMenuItem MenuLaporanTransaksi;
    private javax.swing.JMenuItem MenuLogOut;
    private javax.swing.JMenuItem MenuMasterBarang;
    private javax.swing.JMenuItem MenuMasterPelanggan;
    public javax.swing.JMenuItem MenuTambahUser;
    private javax.swing.JMenuItem MenuTentangAplikasi;
    private javax.swing.JMenuItem MenuTentangDeveloper;
    private javax.swing.JMenuItem MenuTransaksiPenjualan;
    public javax.swing.JMenuItem MenuUlasan;
    private javax.swing.JMenu Tentang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel tfemail;
    public javax.swing.JLabel tflevel;
    public javax.swing.JLabel tfuser;
    // End of variables declaration//GEN-END:variables
}
